name: CI
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golang_ci_lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
